[package]
name = "sieve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#add dependency on num_bigint
num-bigint = "0.4.3"
lazy_static = "1.4.0"

